# Linear algebra

In [1]:
import numpy as np

In [2]:
v = np.random.randint(10, size=(3,))
m = np.random.randint(10, size=(5, 3))

In [3]:
m

array([[5, 5, 4],
       [2, 3, 0],
       [4, 8, 3],
       [5, 7, 9],
       [1, 2, 8]])

In [4]:
v

array([9, 8, 4])

## Dot products, determinants, traces

Dot product is available through `np` itself (as it's very common). Note the ordering and dimensions:

In [5]:
np.dot(m, v)

array([101,  42, 112, 137,  57])

In [6]:
np.dot(m, v[:, np.newaxis])

array([[101],
       [ 42],
       [112],
       [137],
       [ 57]])

In [7]:
np.dot(v, m.T)

array([101,  42, 112, 137,  57])

Inverse matrix is straighforward (as almost any other LA operation):

In [ ]:
s = np.random.randint(10, size=(3,3))
s_inv = np.linalg.inv(s)

In [ ]:
s

In [ ]:
s_inv

In [ ]:
s_inv.dtype

In [ ]:
np.dot(s_inv, s)

Determinants and traces are available as well:

In [ ]:
np.linalg.det(s), np.linalg.det(s_inv)  # det(s) == 1 / det(s_inv), btw

In [ ]:
np.trace(s), np.trace(s_inv)

## Eigenvalues, eigenvectors

Eigenvalue decomposition (and other decompositions as well) are available via `eig` and `eigh` functions:

In [ ]:
evals, evectors = np.linalg.eig(s)

In [ ]:
evals

In [ ]:
evectors

In [ ]:
np.allclose(evals.sum(), np.trace(s))  # some simple LA and correct way of comparing floating point numbers

Creating a diagonal matrix from a `1D` array:

In [ ]:
s_diagonal = np.diag(evals)

In [ ]:
s_diagonal

And now our matrix can be decomposed as:
    
$$
s = VEV^{-1}
$$

where $E$ is a diagonal matrix (with eigenvalues on main diagonal), and $V$ is a matrix where columns are eigenvectors.

In [ ]:
np.dot(evectors, np.dot(s_diagonal, np.linalg.inv(evectors)))

In [ ]:
s

In [ ]:
np.allclose(np.dot(evectors, np.dot(s_diagonal, np.linalg.inv(evectors))), s)